services:
  # Service A
  servicea:
    image: 547519647676.dkr.ecr.ap-south-1.amazonaws.com/servicea:latest
    ports:
      - "3001:3001"
    networks:
      - appnet
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=admin

  # Service B
  serviceb:
    image: 547519647676.dkr.ecr.ap-south-1.amazonaws.com/serviceb:latest
    ports:
      - "3002:3002"
    networks:
      - appnet
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=admin

  # Service C
  servicec:
    image: 547519647676.dkr.ecr.ap-south-1.amazonaws.com/servicec:latest
    ports:
      - "3003:3003"
    networks:
      - appnet
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=admin

  # Service D
  serviced:
    image: 547519647676.dkr.ecr.ap-south-1.amazonaws.com/serviced:latest
    ports:
      - "3004:3004"
    networks:
      - appnet
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=admin

  # Service E
  servicee:
    image: 547519647676.dkr.ecr.ap-south-1.amazonaws.com/servicee:latest
    ports:
      - "3005:3004"
    networks:
      - appnet
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=admin

  frontend:
    image: 547519647676.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
    ports:
      - "8081:80"
    networks:
      - appnet
    environment:
      - REACT_APP_SERVICE_A_URL=http://servicea:3001/serviceA
      - REACT_APP_SERVICE_A_HEALTH=http://servicea:3001/health
      - REACT_APP_SERVICE_B_HEALTH=http://serviceb:3002/health
      - REACT_APP_SERVICE_C_HEALTH=http://servicec:3003/health
      - REACT_APP_SERVICE_D_HEALTH=http://serviced:3004/health
      - REACT_APP_SERVICE_E_HEALTH=http://servicee:3005/health
      - REACT_APP_REQUEST_TIMEOUT=15000
      - REACT_APP_ENABLE_DEBUG=true

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet
    ports:
      - "5432:5432"

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data:
    driver: local