name: CI - Build & Push to ECR

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: servicea
            folder: serviceA
          - service: serviceb
            folder: serviceB
          - service: servicec
            folder: serviceC
          - service: serviced
            folder: serviceD
          - service: servicee
            folder: serviceE
          - service: frontend
            folder: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin 547519647676.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t ${{ matrix.service }} ./${{ matrix.folder }}

      - name: Tag image
        run: |
          docker tag ${{ matrix.service }}:latest 547519647676.dkr.ecr.ap-south-1.amazonaws.com/${{ matrix.service }}:latest

      - name: Push to ECR
        run: |
          docker push 547519647676.dkr.ecr.ap-south-1.amazonaws.com/${{ matrix.service }}:latest